# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67be5ae8b4199c498d03dc4e99579b5ecab3e1c350f7059f92c46687316c79a9d2c7ef70459564131e2183be20966351e1a0e1e7a66c7e96f917f0860ea62c0b

test:
  secret_key_base: 28f6315bbf80fda8ffdff6322a5ab0ceeb33725d7c16549c2f1bf0c9ea311aa2a885cf7fc191355ec6806e8ae3ba6ac05d4d97145472a1ac5489a60b4914cbb7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 4c60af2a656d6d41160428d52e5df87b546add7f41b168ebbf44fd68fcde5fab47d835ee0f0bc80c562c9c639c27ae338ef436de42c317dfcf42b88a7fc68ec2
